pipeline {
    agent any

    environment {
        IMAGE_TAG = 'v1.0.0'
    }


    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }


        stage('Build') {
            steps {
                echo 'Building the application...'
                sh 'chmod +x scripts/build.sh'
                sh './scripts/build.sh'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'chmod +x scripts/test.sh'
                sh './scripts/test.sh'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                //sh "docker build -t my-app:${env.BRANCH_NAME}-${env.BUILD_ID} ."
                //sh "docker build -t my-app:${env.BRANCH_NAME}-${env.BUILD_ID} -t my-app:${IMAGE_TAG} ."
                sh "docker build -t my-app-${env.BRANCH_NAME}:${IMAGE_TAG} ."
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Set the application port based on the branch name
                    def appPort = (env.BRANCH_NAME == 'main') ? '3000' : '3001'
                    echo "Deploying on port ${appPort}..."
                    /*sh """
                    docker run -d -p ${appPort}:${appPort} -e PORT=${appPort} --name my-app-${env.BRANCH_NAME} my-app:${env.BRANCH_NAME}-${env.BUILD_ID}
                    """*/
                    sh "docker run -d -p ${appPort}:${appPort} -e PORT=${appPort} --name my-app-${env.BRANCH_NAME} my-app-${env.BRANCH_NAME}:${IMAGE_TAG}"
                    echo "Application deployed at http://localhost:${appPort}"
                }
            }
        }
    }
}
