pipeline {
    agent any

    environment {
        APP_PORT = '3000'
        IMAGE_TAG = 'v1.0.0'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                }
            }
        

        stage('Build') {
            steps {
                echo 'Building the application...'
                sh 'chmod +x scripts/build.sh'
                sh './scripts/build.sh'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'chmod +x scripts/test.sh'
                sh './scripts/test.sh'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh "docker build -t my-app:${env.IMAGE_TAG} ."
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "Deploying on port ${env.APP_PORT}..."
                    docker run -d -p ${env.APP_PORT}:${env.APP_PORT} --name my-app-${env.IMAGE_TAG} my-app:${env.IMAGE_TAG}
                    echo "Application deployed at http://localhost:${env.APP_PORT}"
                }
            }
        }
    }

}
